# app/services/broker/base.py
from typing import Literal, Optional, List, Dict

Side = Literal["buy","sell"]
TimeInForce = Literal["day","gtc"]

class BrokerBase:
    async def get_account(self) -> dict: ...
    async def get_positions(self) -> list[dict]: ...
    async def place_order(self, symbol: str, qty: float, side: Side, tif: TimeInForce="day", type="market", limit_price: Optional[float]=None) -> dict: ...
    async def cancel_order(self, order_id: str) -> dict: ...
